#include "../luabindings.h"
#include "../defs/CharaInitParam.h"

namespace paramadjuster::params {

void registerCharaInitParam(sol::state *state, sol::table &paramsTable) {
    auto delayInit = [state, &paramsTable]() {
        if (sol::optional<sol::table> usertype = (*state)["CharaInitParam"]; usertype) return;
        auto indexerCharaInitParam = state->new_usertype<ParamTableIndexer<CharaInitParam>>("CharaInitParamTableIndexer");
        indexerCharaInitParam["count"] = sol::property(&ParamTableIndexer<CharaInitParam>::count);
        indexerCharaInitParam["__index"] = &ParamTableIndexer<CharaInitParam>::at;
        indexerCharaInitParam["id"] = &ParamTableIndexer<CharaInitParam>::paramId;
        indexerCharaInitParam["get"] = &ParamTableIndexer<CharaInitParam>::get;
        auto utCharaInitParam = state->new_usertype<CharaInitParam>("CharaInitParam");
        utCharaInitParam["baseRec_mp"] = &CharaInitParam::baseRec_mp;
        utCharaInitParam["baseRec_sp"] = &CharaInitParam::baseRec_sp;
        utCharaInitParam["red_Falldam"] = &CharaInitParam::red_Falldam;
        utCharaInitParam["soul"] = &CharaInitParam::soul;
        utCharaInitParam["equip_Wep_Right"] = &CharaInitParam::equip_Wep_Right;
        utCharaInitParam["equip_Subwep_Right"] = &CharaInitParam::equip_Subwep_Right;
        utCharaInitParam["equip_Wep_Left"] = &CharaInitParam::equip_Wep_Left;
        utCharaInitParam["equip_Subwep_Left"] = &CharaInitParam::equip_Subwep_Left;
        utCharaInitParam["equip_Helm"] = &CharaInitParam::equip_Helm;
        utCharaInitParam["equip_Armer"] = &CharaInitParam::equip_Armer;
        utCharaInitParam["equip_Gaunt"] = &CharaInitParam::equip_Gaunt;
        utCharaInitParam["equip_Leg"] = &CharaInitParam::equip_Leg;
        utCharaInitParam["equip_Arrow"] = &CharaInitParam::equip_Arrow;
        utCharaInitParam["equip_Bolt"] = &CharaInitParam::equip_Bolt;
        utCharaInitParam["equip_SubArrow"] = &CharaInitParam::equip_SubArrow;
        utCharaInitParam["equip_SubBolt"] = &CharaInitParam::equip_SubBolt;
        utCharaInitParam["equip_Accessory01"] = &CharaInitParam::equip_Accessory01;
        utCharaInitParam["equip_Accessory02"] = &CharaInitParam::equip_Accessory02;
        utCharaInitParam["equip_Accessory03"] = &CharaInitParam::equip_Accessory03;
        utCharaInitParam["equip_Accessory04"] = &CharaInitParam::equip_Accessory04;
        utCharaInitParam["unknown_0x50"] = &CharaInitParam::unknown_0x50;
        utCharaInitParam["unknown_0x51"] = &CharaInitParam::unknown_0x51;
        utCharaInitParam["elixir_material00"] = &CharaInitParam::elixir_material00;
        utCharaInitParam["elixir_material01"] = &CharaInitParam::elixir_material01;
        utCharaInitParam["elixir_material02"] = &CharaInitParam::elixir_material02;
        utCharaInitParam["equip_Spell_01"] = &CharaInitParam::equip_Spell_01;
        utCharaInitParam["equip_Spell_02"] = &CharaInitParam::equip_Spell_02;
        utCharaInitParam["equip_Spell_03"] = &CharaInitParam::equip_Spell_03;
        utCharaInitParam["equip_Spell_04"] = &CharaInitParam::equip_Spell_04;
        utCharaInitParam["equip_Spell_05"] = &CharaInitParam::equip_Spell_05;
        utCharaInitParam["equip_Spell_06"] = &CharaInitParam::equip_Spell_06;
        utCharaInitParam["equip_Spell_07"] = &CharaInitParam::equip_Spell_07;
        utCharaInitParam["item_01"] = &CharaInitParam::item_01;
        utCharaInitParam["item_02"] = &CharaInitParam::item_02;
        utCharaInitParam["item_03"] = &CharaInitParam::item_03;
        utCharaInitParam["item_04"] = &CharaInitParam::item_04;
        utCharaInitParam["item_05"] = &CharaInitParam::item_05;
        utCharaInitParam["item_06"] = &CharaInitParam::item_06;
        utCharaInitParam["item_07"] = &CharaInitParam::item_07;
        utCharaInitParam["item_08"] = &CharaInitParam::item_08;
        utCharaInitParam["item_09"] = &CharaInitParam::item_09;
        utCharaInitParam["item_10"] = &CharaInitParam::item_10;
        utCharaInitParam["npcPlayerFaceGenId"] = &CharaInitParam::npcPlayerFaceGenId;
        utCharaInitParam["npcPlayerThinkId"] = &CharaInitParam::npcPlayerThinkId;
        utCharaInitParam["baseHp"] = &CharaInitParam::baseHp;
        utCharaInitParam["baseMp"] = &CharaInitParam::baseMp;
        utCharaInitParam["baseSp"] = &CharaInitParam::baseSp;
        utCharaInitParam["arrowNum"] = &CharaInitParam::arrowNum;
        utCharaInitParam["boltNum"] = &CharaInitParam::boltNum;
        utCharaInitParam["subArrowNum"] = &CharaInitParam::subArrowNum;
        utCharaInitParam["subBoltNum"] = &CharaInitParam::subBoltNum;
        utCharaInitParam["soulLv"] = &CharaInitParam::soulLv;
        utCharaInitParam["baseVit"] = &CharaInitParam::baseVit;
        utCharaInitParam["baseWil"] = &CharaInitParam::baseWil;
        utCharaInitParam["baseEnd"] = &CharaInitParam::baseEnd;
        utCharaInitParam["baseStr"] = &CharaInitParam::baseStr;
        utCharaInitParam["baseDex"] = &CharaInitParam::baseDex;
        utCharaInitParam["baseMag"] = &CharaInitParam::baseMag;
        utCharaInitParam["baseFai"] = &CharaInitParam::baseFai;
        utCharaInitParam["baseLuc"] = &CharaInitParam::baseLuc;
        utCharaInitParam["baseHeroPoint"] = &CharaInitParam::baseHeroPoint;
        utCharaInitParam["baseDurability"] = &CharaInitParam::baseDurability;
        utCharaInitParam["itemNum_01"] = &CharaInitParam::itemNum_01;
        utCharaInitParam["itemNum_02"] = &CharaInitParam::itemNum_02;
        utCharaInitParam["itemNum_03"] = &CharaInitParam::itemNum_03;
        utCharaInitParam["itemNum_04"] = &CharaInitParam::itemNum_04;
        utCharaInitParam["itemNum_05"] = &CharaInitParam::itemNum_05;
        utCharaInitParam["itemNum_06"] = &CharaInitParam::itemNum_06;
        utCharaInitParam["itemNum_07"] = &CharaInitParam::itemNum_07;
        utCharaInitParam["itemNum_08"] = &CharaInitParam::itemNum_08;
        utCharaInitParam["itemNum_09"] = &CharaInitParam::itemNum_09;
        utCharaInitParam["itemNum_10"] = &CharaInitParam::itemNum_10;
        utCharaInitParam["gestureId0"] = &CharaInitParam::gestureId0;
        utCharaInitParam["gestureId1"] = &CharaInitParam::gestureId1;
        utCharaInitParam["gestureId2"] = &CharaInitParam::gestureId2;
        utCharaInitParam["gestureId3"] = &CharaInitParam::gestureId3;
        utCharaInitParam["gestureId4"] = &CharaInitParam::gestureId4;
        utCharaInitParam["gestureId5"] = &CharaInitParam::gestureId5;
        utCharaInitParam["gestureId6"] = &CharaInitParam::gestureId6;
        utCharaInitParam["npcPlayerType"] = &CharaInitParam::npcPlayerType;
        utCharaInitParam["npcPlayerDrawType"] = &CharaInitParam::npcPlayerDrawType;
        utCharaInitParam["npcPlayerSex"] = &CharaInitParam::npcPlayerSex;
        utCharaInitParam["vowType"] = sol::property([](CharaInitParam &param) -> uint8_t { return param.vowType; }, [](CharaInitParam &param, uint8_t value) { param.vowType = value; });
        utCharaInitParam["isSyncTarget"] = sol::property([](CharaInitParam &param) -> uint8_t { return param.isSyncTarget; }, [](CharaInitParam &param, uint8_t value) { param.isSyncTarget = value; });
        utCharaInitParam["wepParamType_Right1"] = &CharaInitParam::wepParamType_Right1;
        utCharaInitParam["wepParamType_Right2"] = &CharaInitParam::wepParamType_Right2;
        utCharaInitParam["wepParamType_Right3"] = &CharaInitParam::wepParamType_Right3;
        utCharaInitParam["wepParamType_Left1"] = &CharaInitParam::wepParamType_Left1;
        utCharaInitParam["wepParamType_Left2"] = &CharaInitParam::wepParamType_Left2;
        utCharaInitParam["wepParamType_Left3"] = &CharaInitParam::wepParamType_Left3;
        utCharaInitParam["equip_Subwep_Right3"] = &CharaInitParam::equip_Subwep_Right3;
        utCharaInitParam["equip_Subwep_Left3"] = &CharaInitParam::equip_Subwep_Left3;
        utCharaInitParam["secondaryItem_01"] = &CharaInitParam::secondaryItem_01;
        utCharaInitParam["secondaryItem_02"] = &CharaInitParam::secondaryItem_02;
        utCharaInitParam["secondaryItem_03"] = &CharaInitParam::secondaryItem_03;
        utCharaInitParam["secondaryItem_04"] = &CharaInitParam::secondaryItem_04;
        utCharaInitParam["secondaryItem_05"] = &CharaInitParam::secondaryItem_05;
        utCharaInitParam["secondaryItem_06"] = &CharaInitParam::secondaryItem_06;
        utCharaInitParam["secondaryItemNum_01"] = &CharaInitParam::secondaryItemNum_01;
        utCharaInitParam["secondaryItemNum_02"] = &CharaInitParam::secondaryItemNum_02;
        utCharaInitParam["secondaryItemNum_03"] = &CharaInitParam::secondaryItemNum_03;
        utCharaInitParam["secondaryItemNum_04"] = &CharaInitParam::secondaryItemNum_04;
        utCharaInitParam["secondaryItemNum_05"] = &CharaInitParam::secondaryItemNum_05;
        utCharaInitParam["secondaryItemNum_06"] = &CharaInitParam::secondaryItemNum_06;
        utCharaInitParam["HpEstMax"] = &CharaInitParam::HpEstMax;
        utCharaInitParam["MpEstMax"] = &CharaInitParam::MpEstMax;
        utCharaInitParam["voiceType"] = &CharaInitParam::voiceType;
    };
    auto tableLoader = [delayInit = std::move(delayInit)]() -> auto { delayInit(); return std::make_unique<ParamTableIndexer<CharaInitParam>>(gParamMgr.findTable(L"CharaInitParam")); };
    paramsTable["CharaInitParam"] = tableLoader;
}

}
