#include "../luabindings.h"
#include "../defs/EquipParamProtector.h"

namespace paramadjuster::params {

void registerEquipParamProtector(sol::state *state, sol::table &paramsTable) {
    auto delayInit = [state, &paramsTable]() {
        if (sol::optional<sol::table> usertype = (*state)["EquipParamProtector"]; usertype) return;
        auto indexerEquipParamProtector = state->new_usertype<ParamTableIndexer<EquipParamProtector>>("EquipParamProtectorTableIndexer");
        indexerEquipParamProtector["count"] = sol::property(&ParamTableIndexer<EquipParamProtector>::count);
        indexerEquipParamProtector["__index"] = &ParamTableIndexer<EquipParamProtector>::at;
        indexerEquipParamProtector["id"] = &ParamTableIndexer<EquipParamProtector>::paramId;
        indexerEquipParamProtector["get"] = &ParamTableIndexer<EquipParamProtector>::get;
        auto utEquipParamProtector = state->new_usertype<EquipParamProtector>("EquipParamProtector");
        utEquipParamProtector["disableParam_NT"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.disableParam_NT; }, [](EquipParamProtector &param, uint8_t value) { param.disableParam_NT = value; });
        utEquipParamProtector["sortId"] = &EquipParamProtector::sortId;
        utEquipParamProtector["wanderingEquipId"] = &EquipParamProtector::wanderingEquipId;
        utEquipParamProtector["resistSleep"] = &EquipParamProtector::resistSleep;
        utEquipParamProtector["resistMadness"] = &EquipParamProtector::resistMadness;
        utEquipParamProtector["saDurability"] = &EquipParamProtector::saDurability;
        utEquipParamProtector["toughnessCorrectRate"] = &EquipParamProtector::toughnessCorrectRate;
        utEquipParamProtector["fixPrice"] = &EquipParamProtector::fixPrice;
        utEquipParamProtector["basicPrice"] = &EquipParamProtector::basicPrice;
        utEquipParamProtector["sellValue"] = &EquipParamProtector::sellValue;
        utEquipParamProtector["weight"] = &EquipParamProtector::weight;
        utEquipParamProtector["residentSpEffectId"] = &EquipParamProtector::residentSpEffectId;
        utEquipParamProtector["residentSpEffectId2"] = &EquipParamProtector::residentSpEffectId2;
        utEquipParamProtector["residentSpEffectId3"] = &EquipParamProtector::residentSpEffectId3;
        utEquipParamProtector["materialSetId"] = &EquipParamProtector::materialSetId;
        utEquipParamProtector["partsDamageRate"] = &EquipParamProtector::partsDamageRate;
        utEquipParamProtector["corectSARecover"] = &EquipParamProtector::corectSARecover;
        utEquipParamProtector["originEquipPro"] = &EquipParamProtector::originEquipPro;
        utEquipParamProtector["originEquipPro1"] = &EquipParamProtector::originEquipPro1;
        utEquipParamProtector["originEquipPro2"] = &EquipParamProtector::originEquipPro2;
        utEquipParamProtector["originEquipPro3"] = &EquipParamProtector::originEquipPro3;
        utEquipParamProtector["originEquipPro4"] = &EquipParamProtector::originEquipPro4;
        utEquipParamProtector["originEquipPro5"] = &EquipParamProtector::originEquipPro5;
        utEquipParamProtector["originEquipPro6"] = &EquipParamProtector::originEquipPro6;
        utEquipParamProtector["originEquipPro7"] = &EquipParamProtector::originEquipPro7;
        utEquipParamProtector["originEquipPro8"] = &EquipParamProtector::originEquipPro8;
        utEquipParamProtector["originEquipPro9"] = &EquipParamProtector::originEquipPro9;
        utEquipParamProtector["originEquipPro10"] = &EquipParamProtector::originEquipPro10;
        utEquipParamProtector["originEquipPro11"] = &EquipParamProtector::originEquipPro11;
        utEquipParamProtector["originEquipPro12"] = &EquipParamProtector::originEquipPro12;
        utEquipParamProtector["originEquipPro13"] = &EquipParamProtector::originEquipPro13;
        utEquipParamProtector["originEquipPro14"] = &EquipParamProtector::originEquipPro14;
        utEquipParamProtector["originEquipPro15"] = &EquipParamProtector::originEquipPro15;
        utEquipParamProtector["faceScaleM_ScaleX"] = &EquipParamProtector::faceScaleM_ScaleX;
        utEquipParamProtector["faceScaleM_ScaleZ"] = &EquipParamProtector::faceScaleM_ScaleZ;
        utEquipParamProtector["faceScaleM_MaxX"] = &EquipParamProtector::faceScaleM_MaxX;
        utEquipParamProtector["faceScaleM_MaxZ"] = &EquipParamProtector::faceScaleM_MaxZ;
        utEquipParamProtector["faceScaleF_ScaleX"] = &EquipParamProtector::faceScaleF_ScaleX;
        utEquipParamProtector["faceScaleF_ScaleZ"] = &EquipParamProtector::faceScaleF_ScaleZ;
        utEquipParamProtector["faceScaleF_MaxX"] = &EquipParamProtector::faceScaleF_MaxX;
        utEquipParamProtector["faceScaleF_MaxZ"] = &EquipParamProtector::faceScaleF_MaxZ;
        utEquipParamProtector["qwcId"] = &EquipParamProtector::qwcId;
        utEquipParamProtector["equipModelId"] = &EquipParamProtector::equipModelId;
        utEquipParamProtector["iconIdM"] = &EquipParamProtector::iconIdM;
        utEquipParamProtector["iconIdF"] = &EquipParamProtector::iconIdF;
        utEquipParamProtector["knockBack"] = &EquipParamProtector::knockBack;
        utEquipParamProtector["knockbackBounceRate"] = &EquipParamProtector::knockbackBounceRate;
        utEquipParamProtector["durability"] = &EquipParamProtector::durability;
        utEquipParamProtector["durabilityMax"] = &EquipParamProtector::durabilityMax;
        utEquipParamProtector["defFlickPower"] = &EquipParamProtector::defFlickPower;
        utEquipParamProtector["defensePhysics"] = &EquipParamProtector::defensePhysics;
        utEquipParamProtector["defenseMagic"] = &EquipParamProtector::defenseMagic;
        utEquipParamProtector["defenseFire"] = &EquipParamProtector::defenseFire;
        utEquipParamProtector["defenseThunder"] = &EquipParamProtector::defenseThunder;
        utEquipParamProtector["defenseSlash"] = &EquipParamProtector::defenseSlash;
        utEquipParamProtector["defenseBlow"] = &EquipParamProtector::defenseBlow;
        utEquipParamProtector["defenseThrust"] = &EquipParamProtector::defenseThrust;
        utEquipParamProtector["resistPoison"] = &EquipParamProtector::resistPoison;
        utEquipParamProtector["resistDisease"] = &EquipParamProtector::resistDisease;
        utEquipParamProtector["resistBlood"] = &EquipParamProtector::resistBlood;
        utEquipParamProtector["resistCurse"] = &EquipParamProtector::resistCurse;
        utEquipParamProtector["reinforceTypeId"] = &EquipParamProtector::reinforceTypeId;
        utEquipParamProtector["trophySGradeId"] = &EquipParamProtector::trophySGradeId;
        utEquipParamProtector["shopLv"] = &EquipParamProtector::shopLv;
        utEquipParamProtector["knockbackParamId"] = &EquipParamProtector::knockbackParamId;
        utEquipParamProtector["flickDamageCutRate"] = &EquipParamProtector::flickDamageCutRate;
        utEquipParamProtector["equipModelCategory"] = &EquipParamProtector::equipModelCategory;
        utEquipParamProtector["equipModelGender"] = &EquipParamProtector::equipModelGender;
        utEquipParamProtector["protectorCategory"] = &EquipParamProtector::protectorCategory;
        utEquipParamProtector["rarity"] = &EquipParamProtector::rarity;
        utEquipParamProtector["sortGroupId"] = &EquipParamProtector::sortGroupId;
        utEquipParamProtector["partsDmgType"] = &EquipParamProtector::partsDmgType;
        utEquipParamProtector["isDeposit"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.isDeposit; }, [](EquipParamProtector &param, uint8_t value) { param.isDeposit = value; });
        utEquipParamProtector["headEquip"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.headEquip; }, [](EquipParamProtector &param, uint8_t value) { param.headEquip = value; });
        utEquipParamProtector["bodyEquip"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.bodyEquip; }, [](EquipParamProtector &param, uint8_t value) { param.bodyEquip = value; });
        utEquipParamProtector["armEquip"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.armEquip; }, [](EquipParamProtector &param, uint8_t value) { param.armEquip = value; });
        utEquipParamProtector["legEquip"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.legEquip; }, [](EquipParamProtector &param, uint8_t value) { param.legEquip = value; });
        utEquipParamProtector["useFaceScale"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.useFaceScale; }, [](EquipParamProtector &param, uint8_t value) { param.useFaceScale = value; });
        utEquipParamProtector["isSkipWeakDamageAnim"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.isSkipWeakDamageAnim; }, [](EquipParamProtector &param, uint8_t value) { param.isSkipWeakDamageAnim = value; });
        utEquipParamProtector["defenseMaterialVariationValue_Weak"] = &EquipParamProtector::defenseMaterialVariationValue_Weak;
        utEquipParamProtector["autoFootEffectDecalBaseId2"] = &EquipParamProtector::autoFootEffectDecalBaseId2;
        utEquipParamProtector["autoFootEffectDecalBaseId3"] = &EquipParamProtector::autoFootEffectDecalBaseId3;
        utEquipParamProtector["defenseMaterialVariationValue"] = &EquipParamProtector::defenseMaterialVariationValue;
        utEquipParamProtector["isDiscard"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.isDiscard; }, [](EquipParamProtector &param, uint8_t value) { param.isDiscard = value; });
        utEquipParamProtector["isDrop"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.isDrop; }, [](EquipParamProtector &param, uint8_t value) { param.isDrop = value; });
        utEquipParamProtector["disableMultiDropShare"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.disableMultiDropShare; }, [](EquipParamProtector &param, uint8_t value) { param.disableMultiDropShare = value; });
        utEquipParamProtector["simpleModelForDlc"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.simpleModelForDlc; }, [](EquipParamProtector &param, uint8_t value) { param.simpleModelForDlc = value; });
        utEquipParamProtector["showLogCondType"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.showLogCondType; }, [](EquipParamProtector &param, uint8_t value) { param.showLogCondType = value; });
        utEquipParamProtector["showDialogCondType"] = sol::property([](EquipParamProtector &param) -> uint8_t { return param.showDialogCondType; }, [](EquipParamProtector &param, uint8_t value) { param.showDialogCondType = value; });
        utEquipParamProtector["neutralDamageCutRate"] = &EquipParamProtector::neutralDamageCutRate;
        utEquipParamProtector["slashDamageCutRate"] = &EquipParamProtector::slashDamageCutRate;
        utEquipParamProtector["blowDamageCutRate"] = &EquipParamProtector::blowDamageCutRate;
        utEquipParamProtector["thrustDamageCutRate"] = &EquipParamProtector::thrustDamageCutRate;
        utEquipParamProtector["magicDamageCutRate"] = &EquipParamProtector::magicDamageCutRate;
        utEquipParamProtector["fireDamageCutRate"] = &EquipParamProtector::fireDamageCutRate;
        utEquipParamProtector["thunderDamageCutRate"] = &EquipParamProtector::thunderDamageCutRate;
        utEquipParamProtector["defenseMaterialSfx1"] = &EquipParamProtector::defenseMaterialSfx1;
        utEquipParamProtector["defenseMaterialSfx_Weak1"] = &EquipParamProtector::defenseMaterialSfx_Weak1;
        utEquipParamProtector["defenseMaterial1"] = &EquipParamProtector::defenseMaterial1;
        utEquipParamProtector["defenseMaterial_Weak1"] = &EquipParamProtector::defenseMaterial_Weak1;
        utEquipParamProtector["defenseMaterialSfx2"] = &EquipParamProtector::defenseMaterialSfx2;
        utEquipParamProtector["defenseMaterialSfx_Weak2"] = &EquipParamProtector::defenseMaterialSfx_Weak2;
        utEquipParamProtector["footMaterialSe"] = &EquipParamProtector::footMaterialSe;
        utEquipParamProtector["defenseMaterial_Weak2"] = &EquipParamProtector::defenseMaterial_Weak2;
        utEquipParamProtector["autoFootEffectDecalBaseId1"] = &EquipParamProtector::autoFootEffectDecalBaseId1;
        utEquipParamProtector["toughnessDamageCutRate"] = &EquipParamProtector::toughnessDamageCutRate;
        utEquipParamProtector["toughnessRecoverCorrection"] = &EquipParamProtector::toughnessRecoverCorrection;
        utEquipParamProtector["darkDamageCutRate"] = &EquipParamProtector::darkDamageCutRate;
        utEquipParamProtector["defenseDark"] = &EquipParamProtector::defenseDark;
        utEquipParamProtector["postureControlId"] = &EquipParamProtector::postureControlId;
        utEquipParamProtector["saleValue"] = &EquipParamProtector::saleValue;
        utEquipParamProtector["resistFreeze"] = &EquipParamProtector::resistFreeze;
        utEquipParamProtector["invisibleFlag_SexVer00"] = &EquipParamProtector::invisibleFlag_SexVer00;
        utEquipParamProtector["invisibleFlag_SexVer01"] = &EquipParamProtector::invisibleFlag_SexVer01;
        utEquipParamProtector["invisibleFlag_SexVer02"] = &EquipParamProtector::invisibleFlag_SexVer02;
        utEquipParamProtector["invisibleFlag_SexVer03"] = &EquipParamProtector::invisibleFlag_SexVer03;
        utEquipParamProtector["invisibleFlag_SexVer04"] = &EquipParamProtector::invisibleFlag_SexVer04;
        utEquipParamProtector["invisibleFlag_SexVer05"] = &EquipParamProtector::invisibleFlag_SexVer05;
        utEquipParamProtector["invisibleFlag_SexVer06"] = &EquipParamProtector::invisibleFlag_SexVer06;
        utEquipParamProtector["invisibleFlag_SexVer07"] = &EquipParamProtector::invisibleFlag_SexVer07;
        utEquipParamProtector["invisibleFlag_SexVer08"] = &EquipParamProtector::invisibleFlag_SexVer08;
        utEquipParamProtector["invisibleFlag_SexVer09"] = &EquipParamProtector::invisibleFlag_SexVer09;
        utEquipParamProtector["invisibleFlag_SexVer10"] = &EquipParamProtector::invisibleFlag_SexVer10;
        utEquipParamProtector["invisibleFlag_SexVer11"] = &EquipParamProtector::invisibleFlag_SexVer11;
        utEquipParamProtector["invisibleFlag_SexVer12"] = &EquipParamProtector::invisibleFlag_SexVer12;
        utEquipParamProtector["invisibleFlag_SexVer13"] = &EquipParamProtector::invisibleFlag_SexVer13;
        utEquipParamProtector["invisibleFlag_SexVer14"] = &EquipParamProtector::invisibleFlag_SexVer14;
        utEquipParamProtector["invisibleFlag_SexVer15"] = &EquipParamProtector::invisibleFlag_SexVer15;
        utEquipParamProtector["invisibleFlag_SexVer16"] = &EquipParamProtector::invisibleFlag_SexVer16;
        utEquipParamProtector["invisibleFlag_SexVer17"] = &EquipParamProtector::invisibleFlag_SexVer17;
        utEquipParamProtector["invisibleFlag_SexVer18"] = &EquipParamProtector::invisibleFlag_SexVer18;
        utEquipParamProtector["invisibleFlag_SexVer19"] = &EquipParamProtector::invisibleFlag_SexVer19;
        utEquipParamProtector["invisibleFlag_SexVer20"] = &EquipParamProtector::invisibleFlag_SexVer20;
        utEquipParamProtector["invisibleFlag_SexVer21"] = &EquipParamProtector::invisibleFlag_SexVer21;
        utEquipParamProtector["invisibleFlag_SexVer22"] = &EquipParamProtector::invisibleFlag_SexVer22;
        utEquipParamProtector["invisibleFlag_SexVer23"] = &EquipParamProtector::invisibleFlag_SexVer23;
        utEquipParamProtector["invisibleFlag_SexVer24"] = &EquipParamProtector::invisibleFlag_SexVer24;
        utEquipParamProtector["invisibleFlag_SexVer25"] = &EquipParamProtector::invisibleFlag_SexVer25;
        utEquipParamProtector["invisibleFlag_SexVer26"] = &EquipParamProtector::invisibleFlag_SexVer26;
        utEquipParamProtector["invisibleFlag_SexVer27"] = &EquipParamProtector::invisibleFlag_SexVer27;
        utEquipParamProtector["invisibleFlag_SexVer28"] = &EquipParamProtector::invisibleFlag_SexVer28;
        utEquipParamProtector["invisibleFlag_SexVer29"] = &EquipParamProtector::invisibleFlag_SexVer29;
        utEquipParamProtector["invisibleFlag_SexVer30"] = &EquipParamProtector::invisibleFlag_SexVer30;
        utEquipParamProtector["invisibleFlag_SexVer31"] = &EquipParamProtector::invisibleFlag_SexVer31;
        utEquipParamProtector["invisibleFlag_SexVer32"] = &EquipParamProtector::invisibleFlag_SexVer32;
        utEquipParamProtector["invisibleFlag_SexVer33"] = &EquipParamProtector::invisibleFlag_SexVer33;
        utEquipParamProtector["invisibleFlag_SexVer34"] = &EquipParamProtector::invisibleFlag_SexVer34;
        utEquipParamProtector["invisibleFlag_SexVer35"] = &EquipParamProtector::invisibleFlag_SexVer35;
        utEquipParamProtector["invisibleFlag_SexVer36"] = &EquipParamProtector::invisibleFlag_SexVer36;
        utEquipParamProtector["invisibleFlag_SexVer37"] = &EquipParamProtector::invisibleFlag_SexVer37;
        utEquipParamProtector["invisibleFlag_SexVer38"] = &EquipParamProtector::invisibleFlag_SexVer38;
        utEquipParamProtector["invisibleFlag_SexVer39"] = &EquipParamProtector::invisibleFlag_SexVer39;
        utEquipParamProtector["invisibleFlag_SexVer40"] = &EquipParamProtector::invisibleFlag_SexVer40;
        utEquipParamProtector["invisibleFlag_SexVer41"] = &EquipParamProtector::invisibleFlag_SexVer41;
        utEquipParamProtector["invisibleFlag_SexVer42"] = &EquipParamProtector::invisibleFlag_SexVer42;
        utEquipParamProtector["invisibleFlag_SexVer43"] = &EquipParamProtector::invisibleFlag_SexVer43;
        utEquipParamProtector["invisibleFlag_SexVer44"] = &EquipParamProtector::invisibleFlag_SexVer44;
        utEquipParamProtector["invisibleFlag_SexVer45"] = &EquipParamProtector::invisibleFlag_SexVer45;
        utEquipParamProtector["invisibleFlag_SexVer46"] = &EquipParamProtector::invisibleFlag_SexVer46;
        utEquipParamProtector["invisibleFlag_SexVer47"] = &EquipParamProtector::invisibleFlag_SexVer47;
        utEquipParamProtector["invisibleFlag_SexVer48"] = &EquipParamProtector::invisibleFlag_SexVer48;
        utEquipParamProtector["invisibleFlag_SexVer49"] = &EquipParamProtector::invisibleFlag_SexVer49;
        utEquipParamProtector["invisibleFlag_SexVer50"] = &EquipParamProtector::invisibleFlag_SexVer50;
        utEquipParamProtector["invisibleFlag_SexVer51"] = &EquipParamProtector::invisibleFlag_SexVer51;
        utEquipParamProtector["invisibleFlag_SexVer52"] = &EquipParamProtector::invisibleFlag_SexVer52;
        utEquipParamProtector["invisibleFlag_SexVer53"] = &EquipParamProtector::invisibleFlag_SexVer53;
        utEquipParamProtector["invisibleFlag_SexVer54"] = &EquipParamProtector::invisibleFlag_SexVer54;
        utEquipParamProtector["invisibleFlag_SexVer55"] = &EquipParamProtector::invisibleFlag_SexVer55;
        utEquipParamProtector["invisibleFlag_SexVer56"] = &EquipParamProtector::invisibleFlag_SexVer56;
        utEquipParamProtector["invisibleFlag_SexVer57"] = &EquipParamProtector::invisibleFlag_SexVer57;
        utEquipParamProtector["invisibleFlag_SexVer58"] = &EquipParamProtector::invisibleFlag_SexVer58;
        utEquipParamProtector["invisibleFlag_SexVer59"] = &EquipParamProtector::invisibleFlag_SexVer59;
        utEquipParamProtector["invisibleFlag_SexVer60"] = &EquipParamProtector::invisibleFlag_SexVer60;
        utEquipParamProtector["invisibleFlag_SexVer61"] = &EquipParamProtector::invisibleFlag_SexVer61;
        utEquipParamProtector["invisibleFlag_SexVer62"] = &EquipParamProtector::invisibleFlag_SexVer62;
        utEquipParamProtector["invisibleFlag_SexVer63"] = &EquipParamProtector::invisibleFlag_SexVer63;
        utEquipParamProtector["invisibleFlag_SexVer64"] = &EquipParamProtector::invisibleFlag_SexVer64;
        utEquipParamProtector["invisibleFlag_SexVer65"] = &EquipParamProtector::invisibleFlag_SexVer65;
        utEquipParamProtector["invisibleFlag_SexVer66"] = &EquipParamProtector::invisibleFlag_SexVer66;
        utEquipParamProtector["invisibleFlag_SexVer67"] = &EquipParamProtector::invisibleFlag_SexVer67;
        utEquipParamProtector["invisibleFlag_SexVer68"] = &EquipParamProtector::invisibleFlag_SexVer68;
        utEquipParamProtector["invisibleFlag_SexVer69"] = &EquipParamProtector::invisibleFlag_SexVer69;
        utEquipParamProtector["invisibleFlag_SexVer70"] = &EquipParamProtector::invisibleFlag_SexVer70;
        utEquipParamProtector["invisibleFlag_SexVer71"] = &EquipParamProtector::invisibleFlag_SexVer71;
        utEquipParamProtector["invisibleFlag_SexVer72"] = &EquipParamProtector::invisibleFlag_SexVer72;
        utEquipParamProtector["invisibleFlag_SexVer73"] = &EquipParamProtector::invisibleFlag_SexVer73;
        utEquipParamProtector["invisibleFlag_SexVer74"] = &EquipParamProtector::invisibleFlag_SexVer74;
        utEquipParamProtector["invisibleFlag_SexVer75"] = &EquipParamProtector::invisibleFlag_SexVer75;
        utEquipParamProtector["invisibleFlag_SexVer76"] = &EquipParamProtector::invisibleFlag_SexVer76;
        utEquipParamProtector["invisibleFlag_SexVer77"] = &EquipParamProtector::invisibleFlag_SexVer77;
        utEquipParamProtector["invisibleFlag_SexVer78"] = &EquipParamProtector::invisibleFlag_SexVer78;
        utEquipParamProtector["invisibleFlag_SexVer79"] = &EquipParamProtector::invisibleFlag_SexVer79;
        utEquipParamProtector["invisibleFlag_SexVer80"] = &EquipParamProtector::invisibleFlag_SexVer80;
        utEquipParamProtector["invisibleFlag_SexVer81"] = &EquipParamProtector::invisibleFlag_SexVer81;
        utEquipParamProtector["invisibleFlag_SexVer82"] = &EquipParamProtector::invisibleFlag_SexVer82;
        utEquipParamProtector["invisibleFlag_SexVer83"] = &EquipParamProtector::invisibleFlag_SexVer83;
        utEquipParamProtector["invisibleFlag_SexVer84"] = &EquipParamProtector::invisibleFlag_SexVer84;
        utEquipParamProtector["invisibleFlag_SexVer85"] = &EquipParamProtector::invisibleFlag_SexVer85;
        utEquipParamProtector["invisibleFlag_SexVer86"] = &EquipParamProtector::invisibleFlag_SexVer86;
        utEquipParamProtector["invisibleFlag_SexVer87"] = &EquipParamProtector::invisibleFlag_SexVer87;
        utEquipParamProtector["invisibleFlag_SexVer88"] = &EquipParamProtector::invisibleFlag_SexVer88;
        utEquipParamProtector["invisibleFlag_SexVer89"] = &EquipParamProtector::invisibleFlag_SexVer89;
        utEquipParamProtector["invisibleFlag_SexVer90"] = &EquipParamProtector::invisibleFlag_SexVer90;
        utEquipParamProtector["invisibleFlag_SexVer91"] = &EquipParamProtector::invisibleFlag_SexVer91;
        utEquipParamProtector["invisibleFlag_SexVer92"] = &EquipParamProtector::invisibleFlag_SexVer92;
        utEquipParamProtector["invisibleFlag_SexVer93"] = &EquipParamProtector::invisibleFlag_SexVer93;
        utEquipParamProtector["invisibleFlag_SexVer94"] = &EquipParamProtector::invisibleFlag_SexVer94;
        utEquipParamProtector["invisibleFlag_SexVer95"] = &EquipParamProtector::invisibleFlag_SexVer95;
    };
    auto tableLoader = [delayInit = std::move(delayInit)]() -> auto { delayInit(); return std::make_unique<ParamTableIndexer<EquipParamProtector>>(gParamMgr.findTable(L"EquipParamProtector")); };
    paramsTable["EquipParamProtector"] = tableLoader;
}

}
