#include "luabindings.h"

namespace paramadjuster::params {

extern void registerActionButtonParam(sol::state *state, sol::table &paramsTable);
extern void registerAssetGeometryParam(sol::state *state, sol::table &paramsTable);
extern void registerAssetMaterialSfxParam(sol::state *state, sol::table &paramsTable);
extern void registerAssetModelSfxParam(sol::state *state, sol::table &paramsTable);
extern void registerAtkParam(sol::state *state, sol::table &paramsTable);
extern void registerAttackElementCorrectParam(sol::state *state, sol::table &paramsTable);
extern void registerBaseChrSelectMenuParam(sol::state *state, sol::table &paramsTable);
extern void registerBehaviorParam(sol::state *state, sol::table &paramsTable);
extern void registerBonfireWarpParam(sol::state *state, sol::table &paramsTable);
extern void registerBonfireWarpSubCategoryParam(sol::state *state, sol::table &paramsTable);
extern void registerBonfireWarpTabParam(sol::state *state, sol::table &paramsTable);
extern void registerBuddyParam(sol::state *state, sol::table &paramsTable);
extern void registerBuddyStoneParam(sol::state *state, sol::table &paramsTable);
extern void registerBudgetParam(sol::state *state, sol::table &paramsTable);
extern void registerBulletCreateLimitParam(sol::state *state, sol::table &paramsTable);
extern void registerBulletParam(sol::state *state, sol::table &paramsTable);
extern void registerCalcCorrectGraph(sol::state *state, sol::table &paramsTable);
extern void registerCameraFadeParam(sol::state *state, sol::table &paramsTable);
extern void registerCeremonyParam(sol::state *state, sol::table &paramsTable);
extern void registerCharaInitParam(sol::state *state, sol::table &paramsTable);
extern void registerCharMakeMenuListItemParam(sol::state *state, sol::table &paramsTable);
extern void registerCharMakeMenuTopParam(sol::state *state, sol::table &paramsTable);
extern void registerChrActivateConditionParam(sol::state *state, sol::table &paramsTable);
extern void registerChrEquipModelParam(sol::state *state, sol::table &paramsTable);
extern void registerChrModelParam(sol::state *state, sol::table &paramsTable);
extern void registerClearCountCorrectParam(sol::state *state, sol::table &paramsTable);
extern void registerCommonSystemParam(sol::state *state, sol::table &paramsTable);
extern void registerCoolTimeParam(sol::state *state, sol::table &paramsTable);
extern void registerCutsceneGparamTimeParam(sol::state *state, sol::table &paramsTable);
extern void registerCutsceneGparamWeatherParam(sol::state *state, sol::table &paramsTable);
extern void registerCutsceneMapIdParam(sol::state *state, sol::table &paramsTable);
extern void registerCutSceneTextureLoadParam(sol::state *state, sol::table &paramsTable);
extern void registerCutsceneTimezoneConvertParam(sol::state *state, sol::table &paramsTable);
extern void registerCutsceneWeatherOverrideGparamIdConvertParam(sol::state *state, sol::table &paramsTable);
extern void registerDecalParam(sol::state *state, sol::table &paramsTable);
extern void registerDefaultKeyAssign(sol::state *state, sol::table &paramsTable);
extern void registerDirectionCameraParam(sol::state *state, sol::table &paramsTable);
extern void registerEnemyCommonParam(sol::state *state, sol::table &paramsTable);
extern void registerEnvObjLotParam(sol::state *state, sol::table &paramsTable);
extern void registerEquipMtrlSetParam(sol::state *state, sol::table &paramsTable);
extern void registerEquipParamAccessory(sol::state *state, sol::table &paramsTable);
extern void registerEquipParamCustomWeapon(sol::state *state, sol::table &paramsTable);
extern void registerEquipParamGem(sol::state *state, sol::table &paramsTable);
extern void registerEquipParamGoods(sol::state *state, sol::table &paramsTable);
extern void registerEquipParamProtector(sol::state *state, sol::table &paramsTable);
extern void registerEquipParamWeapon(sol::state *state, sol::table &paramsTable);
extern void registerEstusFlaskRecoveryParam(sol::state *state, sol::table &paramsTable);
extern void registerFaceParam(sol::state *state, sol::table &paramsTable);
extern void registerFaceRangeParam(sol::state *state, sol::table &paramsTable);
extern void registerFeTextEffectParam(sol::state *state, sol::table &paramsTable);
extern void registerFinalDamageRateParam(sol::state *state, sol::table &paramsTable);
extern void registerFootSfxParam(sol::state *state, sol::table &paramsTable);
extern void registerGameAreaParam(sol::state *state, sol::table &paramsTable);
extern void registerGestureParam(sol::state *state, sol::table &paramsTable);
extern void registerGparamRefSettingsParam(sol::state *state, sol::table &paramsTable);
extern void registerGrassLodRangeParam(sol::state *state, sol::table &paramsTable);
extern void registerGrassTypeParam(sol::state *state, sol::table &paramsTable);
extern void registerHitEffectSeParam(sol::state *state, sol::table &paramsTable);
extern void registerHitEffectSfxConceptParam(sol::state *state, sol::table &paramsTable);
extern void registerHitEffectSfxParam(sol::state *state, sol::table &paramsTable);
extern void registerHitMtrlParam(sol::state *state, sol::table &paramsTable);
extern void registerItemLotParam(sol::state *state, sol::table &paramsTable);
extern void registerKeyAssignMenuItemParam(sol::state *state, sol::table &paramsTable);
extern void registerKeyAssignParam(sol::state *state, sol::table &paramsTable);
extern void registerKnockBackParam(sol::state *state, sol::table &paramsTable);
extern void registerKnowledgeLoadScreenItemParam(sol::state *state, sol::table &paramsTable);
extern void registerLegacyDistantViewPartsReplaceParam(sol::state *state, sol::table &paramsTable);
extern void registerLockCamParam(sol::state *state, sol::table &paramsTable);
extern void registerMagicParam(sol::state *state, sol::table &paramsTable);
extern void registerMapDefaultInfoParam(sol::state *state, sol::table &paramsTable);
extern void registerMapGdRegionDrawParam(sol::state *state, sol::table &paramsTable);
extern void registerMapGdRegionInfo(sol::state *state, sol::table &paramsTable);
extern void registerMapGridCreateHeightDetailLimitInfo(sol::state *state, sol::table &paramsTable);
extern void registerMapGridCreateHeightLimitInfo(sol::state *state, sol::table &paramsTable);
extern void registerMapMimicryEstablishmentParam(sol::state *state, sol::table &paramsTable);
extern void registerMapNameTexParam(sol::state *state, sol::table &paramsTable);
extern void registerMapNameTexParam_m61(sol::state *state, sol::table &paramsTable);
extern void registerMapPieceTexParam(sol::state *state, sol::table &paramsTable);
extern void registerMapPieceTexParam_m61(sol::state *state, sol::table &paramsTable);
extern void registerMaterialEx(sol::state *state, sol::table &paramsTable);
extern void registerMenuCommonParam(sol::state *state, sol::table &paramsTable);
extern void registerMenuOffscrRendParam(sol::state *state, sol::table &paramsTable);
extern void registerMenuParamColorTable(sol::state *state, sol::table &paramsTable);
extern void registerMenuPropertyLayoutParam(sol::state *state, sol::table &paramsTable);
extern void registerMenuPropertySpecParam(sol::state *state, sol::table &paramsTable);
extern void registerMenuValueTableSpecParam(sol::state *state, sol::table &paramsTable);
extern void registerMimicryEstablishmentTexParam(sol::state *state, sol::table &paramsTable);
extern void registerMimicryEstablishmentTexParam_m61(sol::state *state, sol::table &paramsTable);
extern void registerMoveParam(sol::state *state, sol::table &paramsTable);
extern void registerMultiEstusFlaskBonusParam(sol::state *state, sol::table &paramsTable);
extern void registerMultiPlayCorrectionParam(sol::state *state, sol::table &paramsTable);
extern void registerMultiSoulBonusRateParam(sol::state *state, sol::table &paramsTable);
extern void registerNpcAiActionParam(sol::state *state, sol::table &paramsTable);
extern void registerNpcAiBehaviorProbabilityParam(sol::state *state, sol::table &paramsTable);
extern void registerNpcParam(sol::state *state, sol::table &paramsTable);
extern void registerNpcThinkParam(sol::state *state, sol::table &paramsTable);
extern void registerObjActParam(sol::state *state, sol::table &paramsTable);
extern void registerPartsDrawParam(sol::state *state, sol::table &paramsTable);
extern void registerPhantomParam(sol::state *state, sol::table &paramsTable);
extern void registerPlayerCommonParam(sol::state *state, sol::table &paramsTable);
extern void registerPlayRegionParam(sol::state *state, sol::table &paramsTable);
extern void registerPostureControlParam_Gender(sol::state *state, sol::table &paramsTable);
extern void registerPostureControlParam_Pro(sol::state *state, sol::table &paramsTable);
extern void registerPostureControlParam_WepLeft(sol::state *state, sol::table &paramsTable);
extern void registerPostureControlParam_WepRight(sol::state *state, sol::table &paramsTable);
extern void registerRandomAppearParam(sol::state *state, sol::table &paramsTable);
extern void registerReinforceParamProtector(sol::state *state, sol::table &paramsTable);
extern void registerReinforceParamWeapon(sol::state *state, sol::table &paramsTable);
extern void registerResistCorrectParam(sol::state *state, sol::table &paramsTable);
extern void registerReverbAuxSendBusParam(sol::state *state, sol::table &paramsTable);
extern void registerRideParam(sol::state *state, sol::table &paramsTable);
extern void registerRoleParam(sol::state *state, sol::table &paramsTable);
extern void registerRollingObjLotParam(sol::state *state, sol::table &paramsTable);
extern void registerRuntimeBoneControlParam(sol::state *state, sol::table &paramsTable);
extern void registerSeActivationRangeParam(sol::state *state, sol::table &paramsTable);
extern void registerSeMaterialConvertParam(sol::state *state, sol::table &paramsTable);
extern void registerSfxBlockResShareParam(sol::state *state, sol::table &paramsTable);
extern void registerShopLineupParam(sol::state *state, sol::table &paramsTable);
extern void registerSignPuddleParam(sol::state *state, sol::table &paramsTable);
extern void registerSignPuddleSubCategoryParam(sol::state *state, sol::table &paramsTable);
extern void registerSignPuddleTabParam(sol::state *state, sol::table &paramsTable);
extern void registerSpeedtreeModel(sol::state *state, sol::table &paramsTable);
extern void registerSpEffect(sol::state *state, sol::table &paramsTable);
extern void registerSpEffectSetParam(sol::state *state, sol::table &paramsTable);
extern void registerSpEffectVfx(sol::state *state, sol::table &paramsTable);
extern void registerSwordArtsParam(sol::state *state, sol::table &paramsTable);
extern void registerTalkParam(sol::state *state, sol::table &paramsTable);
extern void registerThrowDirectionSfxParam(sol::state *state, sol::table &paramsTable);
extern void registerThrowParam(sol::state *state, sol::table &paramsTable);
extern void registerToughnessParam(sol::state *state, sol::table &paramsTable);
extern void registerTutorialParam(sol::state *state, sol::table &paramsTable);
extern void registerWaypointParam(sol::state *state, sol::table &paramsTable);
extern void registerWeatherAssetCreateParam(sol::state *state, sol::table &paramsTable);
extern void registerWeatherAssetReplaceParam(sol::state *state, sol::table &paramsTable);
extern void registerWeatherLotParam(sol::state *state, sol::table &paramsTable);
extern void registerWeatherLotTexParam(sol::state *state, sol::table &paramsTable);
extern void registerWeatherLotTexParam_m61(sol::state *state, sol::table &paramsTable);
extern void registerWeatherParam(sol::state *state, sol::table &paramsTable);
extern void registerWepAbsorpPosParam(sol::state *state, sol::table &paramsTable);
extern void registerWetAspectParam(sol::state *state, sol::table &paramsTable);
extern void registerWhiteSignCoolTimeParam(sol::state *state, sol::table &paramsTable);
extern void registerWorldMapLegacyConvParam(sol::state *state, sol::table &paramsTable);
extern void registerWorldMapPieceParam(sol::state *state, sol::table &paramsTable);
extern void registerWorldMapPlaceNameParam(sol::state *state, sol::table &paramsTable);
extern void registerWorldMapPointParam(sol::state *state, sol::table &paramsTable);

void registerAll(sol::state *state, sol::table &paramsTable) {
    registerActionButtonParam(state, paramsTable);
    registerAssetGeometryParam(state, paramsTable);
    registerAssetMaterialSfxParam(state, paramsTable);
    registerAssetModelSfxParam(state, paramsTable);
    registerAtkParam(state, paramsTable);
    registerAttackElementCorrectParam(state, paramsTable);
    registerBaseChrSelectMenuParam(state, paramsTable);
    registerBehaviorParam(state, paramsTable);
    registerBonfireWarpParam(state, paramsTable);
    registerBonfireWarpSubCategoryParam(state, paramsTable);
    registerBonfireWarpTabParam(state, paramsTable);
    registerBuddyParam(state, paramsTable);
    registerBuddyStoneParam(state, paramsTable);
    registerBudgetParam(state, paramsTable);
    registerBulletCreateLimitParam(state, paramsTable);
    registerBulletParam(state, paramsTable);
    registerCalcCorrectGraph(state, paramsTable);
    registerCameraFadeParam(state, paramsTable);
    registerCeremonyParam(state, paramsTable);
    registerCharaInitParam(state, paramsTable);
    registerCharMakeMenuListItemParam(state, paramsTable);
    registerCharMakeMenuTopParam(state, paramsTable);
    registerChrActivateConditionParam(state, paramsTable);
    registerChrEquipModelParam(state, paramsTable);
    registerChrModelParam(state, paramsTable);
    registerClearCountCorrectParam(state, paramsTable);
    registerCommonSystemParam(state, paramsTable);
    registerCoolTimeParam(state, paramsTable);
    registerCutsceneGparamTimeParam(state, paramsTable);
    registerCutsceneGparamWeatherParam(state, paramsTable);
    registerCutsceneMapIdParam(state, paramsTable);
    registerCutSceneTextureLoadParam(state, paramsTable);
    registerCutsceneTimezoneConvertParam(state, paramsTable);
    registerCutsceneWeatherOverrideGparamIdConvertParam(state, paramsTable);
    registerDecalParam(state, paramsTable);
    registerDefaultKeyAssign(state, paramsTable);
    registerDirectionCameraParam(state, paramsTable);
    registerEnemyCommonParam(state, paramsTable);
    registerEnvObjLotParam(state, paramsTable);
    registerEquipMtrlSetParam(state, paramsTable);
    registerEquipParamAccessory(state, paramsTable);
    registerEquipParamCustomWeapon(state, paramsTable);
    registerEquipParamGem(state, paramsTable);
    registerEquipParamGoods(state, paramsTable);
    registerEquipParamProtector(state, paramsTable);
    registerEquipParamWeapon(state, paramsTable);
    registerEstusFlaskRecoveryParam(state, paramsTable);
    registerFaceParam(state, paramsTable);
    registerFaceRangeParam(state, paramsTable);
    registerFeTextEffectParam(state, paramsTable);
    registerFinalDamageRateParam(state, paramsTable);
    registerFootSfxParam(state, paramsTable);
    registerGameAreaParam(state, paramsTable);
    registerGestureParam(state, paramsTable);
    registerGparamRefSettingsParam(state, paramsTable);
    registerGrassLodRangeParam(state, paramsTable);
    registerGrassTypeParam(state, paramsTable);
    registerHitEffectSeParam(state, paramsTable);
    registerHitEffectSfxConceptParam(state, paramsTable);
    registerHitEffectSfxParam(state, paramsTable);
    registerHitMtrlParam(state, paramsTable);
    registerItemLotParam(state, paramsTable);
    registerKeyAssignMenuItemParam(state, paramsTable);
    registerKeyAssignParam(state, paramsTable);
    registerKnockBackParam(state, paramsTable);
    registerKnowledgeLoadScreenItemParam(state, paramsTable);
    registerLegacyDistantViewPartsReplaceParam(state, paramsTable);
    registerLockCamParam(state, paramsTable);
    registerMagicParam(state, paramsTable);
    registerMapDefaultInfoParam(state, paramsTable);
    registerMapGdRegionDrawParam(state, paramsTable);
    registerMapGdRegionInfo(state, paramsTable);
    registerMapGridCreateHeightDetailLimitInfo(state, paramsTable);
    registerMapGridCreateHeightLimitInfo(state, paramsTable);
    registerMapMimicryEstablishmentParam(state, paramsTable);
    registerMapNameTexParam(state, paramsTable);
    registerMapNameTexParam_m61(state, paramsTable);
    registerMapPieceTexParam(state, paramsTable);
    registerMapPieceTexParam_m61(state, paramsTable);
    registerMaterialEx(state, paramsTable);
    registerMenuCommonParam(state, paramsTable);
    registerMenuOffscrRendParam(state, paramsTable);
    registerMenuParamColorTable(state, paramsTable);
    registerMenuPropertyLayoutParam(state, paramsTable);
    registerMenuPropertySpecParam(state, paramsTable);
    registerMenuValueTableSpecParam(state, paramsTable);
    registerMimicryEstablishmentTexParam(state, paramsTable);
    registerMimicryEstablishmentTexParam_m61(state, paramsTable);
    registerMoveParam(state, paramsTable);
    registerMultiEstusFlaskBonusParam(state, paramsTable);
    registerMultiPlayCorrectionParam(state, paramsTable);
    registerMultiSoulBonusRateParam(state, paramsTable);
    registerNpcAiActionParam(state, paramsTable);
    registerNpcAiBehaviorProbabilityParam(state, paramsTable);
    registerNpcParam(state, paramsTable);
    registerNpcThinkParam(state, paramsTable);
    registerObjActParam(state, paramsTable);
    registerPartsDrawParam(state, paramsTable);
    registerPhantomParam(state, paramsTable);
    registerPlayerCommonParam(state, paramsTable);
    registerPlayRegionParam(state, paramsTable);
    registerPostureControlParam_Gender(state, paramsTable);
    registerPostureControlParam_Pro(state, paramsTable);
    registerPostureControlParam_WepLeft(state, paramsTable);
    registerPostureControlParam_WepRight(state, paramsTable);
    registerRandomAppearParam(state, paramsTable);
    registerReinforceParamProtector(state, paramsTable);
    registerReinforceParamWeapon(state, paramsTable);
    registerResistCorrectParam(state, paramsTable);
    registerReverbAuxSendBusParam(state, paramsTable);
    registerRideParam(state, paramsTable);
    registerRoleParam(state, paramsTable);
    registerRollingObjLotParam(state, paramsTable);
    registerRuntimeBoneControlParam(state, paramsTable);
    registerSeActivationRangeParam(state, paramsTable);
    registerSeMaterialConvertParam(state, paramsTable);
    registerSfxBlockResShareParam(state, paramsTable);
    registerShopLineupParam(state, paramsTable);
    registerSignPuddleParam(state, paramsTable);
    registerSignPuddleSubCategoryParam(state, paramsTable);
    registerSignPuddleTabParam(state, paramsTable);
    registerSpeedtreeModel(state, paramsTable);
    registerSpEffect(state, paramsTable);
    registerSpEffectSetParam(state, paramsTable);
    registerSpEffectVfx(state, paramsTable);
    registerSwordArtsParam(state, paramsTable);
    registerTalkParam(state, paramsTable);
    registerThrowDirectionSfxParam(state, paramsTable);
    registerThrowParam(state, paramsTable);
    registerToughnessParam(state, paramsTable);
    registerTutorialParam(state, paramsTable);
    registerWaypointParam(state, paramsTable);
    registerWeatherAssetCreateParam(state, paramsTable);
    registerWeatherAssetReplaceParam(state, paramsTable);
    registerWeatherLotParam(state, paramsTable);
    registerWeatherLotTexParam(state, paramsTable);
    registerWeatherLotTexParam_m61(state, paramsTable);
    registerWeatherParam(state, paramsTable);
    registerWepAbsorpPosParam(state, paramsTable);
    registerWetAspectParam(state, paramsTable);
    registerWhiteSignCoolTimeParam(state, paramsTable);
    registerWorldMapLegacyConvParam(state, paramsTable);
    registerWorldMapPieceParam(state, paramsTable);
    registerWorldMapPlaceNameParam(state, paramsTable);
    registerWorldMapPointParam(state, paramsTable);
}

}
